### ISSUE TITLE
How to change Access control

### ISSUE THREAD

**Issue by foto-andreas** [Whizkidzz/Solaredge#1]
Hi,

tried to login as tech in my SolarEdge inverter. Your tool generates passwords. What are the user names to use?

Andreas

**Comment by foto-andreas** [comment]
`<SNR>` resp `<SNR>-ADV` looks correct ;-)

**Comment by foto-andreas** [comment]
but all settings, options status are the same for all logins :-/

**Comment by Whizkidzz** [comment]
Andreas,

The user name is the ID of the Inverter (all letters in capital e.q. 1A3B567D-AB
So no lower case as in 1a3b567D-AB

With tech and Tech-adv you can change the Grid Parameters
Don't now what the difference is between tech and tech adv
