### ISSUE TITLE
v2 and v3 software

### ISSUE THREAD

**Issue by oliv3r** [Whizkidzz/Solaredge#3]
Hey @Whizkidzz 

i've been searching far and wide, but cannot find anything with regards to the v3 software other then a screenshot of a BETA version in a pdf.

Even the v2 version is not findable anymore. Could you add a zip of the v3 to your repo as well for archival purposes?

**Comment by Whizkidzz** [comment]
Hey Will have a look when i am back Home
Because i lost the install file but maybe we only need the exe and dll’s which i have

**Comment by oliv3r** [comment]
Did you manage to find it? :)

**Comment by oliv3r** [comment]
@Whizkidzz ping :)

**Comment by oliv3r** [comment]
@Whizkidzz pong :p

**Comment by Whizkidzz** [comment]
@oliv3r 

Finally found the installation file for V3 (was still residing in the windows installer directory with a random name)

**Comment by oliv3r** [comment]
issue resolved! awesome :) Thanks a lot!

**Comment by oliv3r** [comment]
I have since found some guy that uploaded a decompiled v2; I've forked it and see if I can do the same with v3.

https://gitlab.com/centraluniverse/inverter_configuration_tool
